---
- hosts: localhost
  gather_facts: no
  become: yes


  tasks:
  - name: Install Nginx Web Server on RedHat Family
    yum:
      name: nginx
      state: latest

  - name: Create home directory for www
    file:
      path: /var/www/
      state: directory

  - name: nginx restart
    service:
      name: nginx
      state: restarted

  - name: check port
    wait_for:
      port: 8080
      delay: 10